### ISSUE TITLE
interface '/api/v1/signature/funcctx' in openapi for sibyl2 server  returns Wrong calling relationships

### ISSUE THREAD

**Issue by Magnibronzeball** [opensibyl/sibyl2#76]
my repo is a java project used springcloud,i chose one signatrue:"jnpf.controller|jnpf.controller.AppMenuController|list|Page|ActionResult" to invoke the api ,and it returns:
`"calls":
[
"jnpf.permission.controller|jnpf.permission.controller.AuthorizeController|getAuthorize|boolean|AuthorizeVO",
"jnpf.base.fallback|jnpf.base.fallback.ModuleApiFallback|getModuleList|String|List<ModuleEntity>",
"com.bstek.ureport.build.cell.right|com.bstek.ureport.build.cell.right.RightDuplocatorWrapper|contains|Cell|boolean",
"jnpf.permission.fallback|jnpf.permission.fallback.AuthorizeApiFallback|getAuthorize|boolean|AuthorizeVO",
"com.bstek.ureport.definition.value|com.bstek.ureport.definition.value.ZxingValue|getCategory||ZxingCategory",
"jnpf.base.controller|jnpf.base.controller.ModuleController|getModuleList|String|List<ModuleEntity>",
"jnpf.permission.service.impl|jnpf.permission.service.impl.AuthorizeServiceImpl|getAuthorize|boolean|AuthorizeVO",
"jnpf.permission.service.impl|jnpf.permission.service.impl.AuthorizeServiceImpl|getAuthorize|UserInfo|AuthorizeVO",
"jnpf.permission|jnpf.permission.AuthorizeApi|getAuthorize|boolean|AuthorizeVO",
"jnpf.provider.permission|jnpf.provider.permission.AuthorizeProvider|getAuthorize|boolean|AuthorizeVO",
"jnpf.base.service|jnpf.base.service.ModuleService|getModuleList|String|List<ModuleEntity>",
"jnpf.permission.util|jnpf.permission.util.AuthorizeUtil|getAuthorize|UserInfo|AuthorizeVO",
"jnpf.base.service.impl|jnpf.base.service.impl.ModuleServiceImpl|getModuleList|String|List<ModuleEntity>",
"com.bstek.ureport.console.util|com.bstek.ureport.console.util.ActionResult|page|List<T>,PaginationVO|<T>",
"jnpf.permission.service|jnpf.permission.service.AuthorizeService|getAuthorize|UserInfo|AuthorizeVO",
"jnpf.permission.util|jnpf.permission.util.AuthorizeUtil|getAuthorize|boolean|AuthorizeVO",
"jnpf.base|jnpf.base.ModuleApi|getModuleList|String|List<ModuleEntity>",
"com.bstek.ureport.build.cell.down|com.bstek.ureport.build.cell.down.DownDuplocatorWrapper|contains|Cell|boolean",
"jnpf.permission.service|jnpf.permission.service.AuthorizeService|getAuthorize|boolean|AuthorizeVO"
],`

infact "jnpf.controller|jnpf.controller.AppMenuController|list|Page|ActionResult" just called "jnpf.permission.service.impl|jnpf.permission.service.impl.AuthorizeServiceImpl|getAuthorize|boolean|AuthorizeVO" one method only ,but it returns：
"jnpf.provider.permission|jnpf.provider.permission.AuthorizeProvider|getAuthorize|boolean|AuthorizeVO",
"jnpf.permission.service.impl|jnpf.permission.service.impl.AuthorizeServiceImpl|getAuthorize|boolean|AuthorizeVO",
"jnpf.permission.service.impl|jnpf.permission.service.impl.AuthorizeServiceImpl|getAuthorize|UserInfo|AuthorizeVO",
"jnpf.permission.controller|jnpf.permission.controller.AuthorizeController|getAuthorize|boolean|AuthorizeVO",
。。。。。 and so on。
it seems that，it just match the short name of the method,but not the full signature. 
please help me ,how can i get the Precision call relationships，thanks very much!

**Comment by williamfzc** [comment]
There is no way to get a `precise` reference graph without a real compilation.
You should take a look on [srctx](https://github.com/williamfzc/srctx) if you prefer a precise call graph.

- https://github.com/opensibyl/sibyl2#overview
- https://github.com/opensibyl/sibyl2/issues/5

**Comment by Magnibronzeball** [comment]
got it，thanks a lot!
